import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Text } from '@chakra-ui/layout'
import Link from 'next/link'

const Home = () => {
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <h1>Welcome to my first Next.js app! SNKRZ</h1>
            <Link href="/sneakers" passHref={true}>
               <Text as="button" fontSize="lg" color="green.300">
                  Get Started Here!
               </Text>
            </Link>
         </main>
      </div>
   )
}

export default Home
